#!/usr/bin/env bash
set -e

PROMETHEUS_CONFIG="$PWD/src/hosts/prometheus.nix"
NIXOS_VERSION=$(cat version)

usage() {
    echo "Usage:"
    echo "   --build Build and switch system"
    echo "   --channels Update channels"
    exit 0
}

if [ "$#" -ne 1 ]; then
    usage
fi

case "$1" in
    --build)
        echo ">> Building from config $PROMETHEUS_CONFIG"
        sudo nixos-rebuild switch -I nixos-config="$PROMETHEUS_CONFIG"
        ;;
    --channels)
        echo ">> Adding channels"
	    sudo nix-channel --add https://github.com/nix-community/home-manager/archive/release-$NIXOS_VERSION.tar.gz home-manager
        sudo nix-channel --update
        ;;
    *)
        usage
        ;;
esac
