# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-dce66f34-c2ba-43e0-ad00-72ad32e2037e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-dce66f34-c2ba-43e0-ad00-72ad32e2037e".device = "/dev/disk/by-uuid/dce66f34-c2ba-43e0-ad00-72ad32e2037e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4BC8-55C2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ffffa5d7-c2ae-46b1-9c5a-8a1cfa3260b9"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
